version: "3.4"
services:
  app:
    build:
      context: .
    command: mix server
    environment:
      - TELEGRAM_NAME=pkgtracker
      - TELEGRAM_TOKEN=
      - MIX_ENV=dev
      - PG_HOST=postgres
      - PG_USERNAME=postgres
      - PG_PASSWORD=postgres
    depends_on:
      - postgres
    volumes:
      - .:/app
    links:
      - postgres
    stdin_open: true
    tty: true

  postgres:
    image: postgres:11
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pkgtracker_dev
    ports:
      - 5432
