version: "3.4"
services:
  app:
    build:
      context: .
    command: mix server
    environment:
      - MIX_ENV=dev
      - PG_HOST=postgres
      - PG_USERNAME=postgres
    depends_on:
      - postgres
    volumes:
      - .:/app
    stdin_open: true
    tty: true

  postgres:
    image: postgres:9.6.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=trackingbot_dev
    ports:
      - 5432:5432
