apiVersion: v1
kind: Pod
metadata:
  name: run-migrations-on-app
  namespace: pkgtracker
spec:
  containers:
  - name: db-migration
    image: basestylo/pkgtracker:1571676896
    resources:
      requests:
        cpu: "10m"
    command: ["mix"]
    args: ["do", "ecto.migrate"]
    env:
      - name: MIX_ENV
        value: prod
      - name: PG_HOST
        value: postgres
      - name: PG_USERNAME
        value: postgres
      - name: DATABASE_URL
        value: "ecto://postgres:postgres@postgres/pkgtracker_prod"
  restartPolicy: Never
